### ISSUE TITLE
Create RDS file for HTAN

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/ProjectLiveData#1]
Acceptance criteria: 
- Get all projects in HTAN
- Get list of manifests via REST API getProjectManifests endpoint (needs to be added)
- Download each manifest via REST API /manifest/download endpoint
- Join every manifest with [fileview](https://www.synapse.org/#!Synapse:syn20446927/tables/)
- Add unknownDataType for all files without manifests
- Convert to RDS
- Store in synapse

**Comment by rrchai** [comment]
question: how does the rds get updated? - Is the rds automatically updated if changes (like monitoring versions). For example, if a user submits a manifest via DCA and they would like to reuse the app, will the rds contains the manifest user just submitted?

**Comment by andrewelamb** [comment]
@rrchai I'll get back to you on this, some of this I'm not sure on yet, and will be cleared up later today.

**Comment by andrewelamb** [comment]
For projectlive before we had a cron job that would recreate the various rds files once a day.

**Comment by andrewelamb** [comment]
@milen-sage I'm needing
- REST API getProjectManifests endpoint
- Download permissions to all HTAN projects

**Comment by milen-sage** [comment]
@andrewelamb FAIR Data (and you) has edit access to all HTAN projects - use responsively :)

Could you start a gh issue on FAIR Data's [backlog](https://github.com/orgs/Sage-Bionetworks/projects/42/views/14?filterQuery=&sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Assignees&visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C1507990%2C1508720%5D) to add the REST API endpoint?

**Comment by andrewelamb** [comment]
@milen-sage 

It looks like I'm missing download access to around half the manifest files, like [this one.](https://www.synapse.org/#!Synapse:syn23636452)

**Comment by andrewelamb** [comment]
@milen-sage I've noticed that some of the values in the manifest get read in an inconsistent manner. Character vs Double. This causes an error when binding them together. I think we will need to make an API call here that's something like:

getAttributeType(manifestID, atrributeName) -> str
(Where string is one of [string, double, integer, logical]



`
# A tibble: 283 × 1
   `Protocol Link`
   **chr**       
 1 Not Applicable 
 2 Not Applicable 
 3 Not Applicable 
 4 Not Applicable 
 5 Not Applicable 
 6 Not Applicable 
 7 Not Applicable 
 8 Not Applicable 
 9 Not Applicable 
10 Not Applicable 
# … with 273 more rows

[[3]]
# A tibble: 214 × 1
   `Protocol Link`
             **dbl**
 1               0
 2               0
 3               0
 4               0
 5               0
 6               0
 7               0
 8               0
 9               0
10               0
# … with 204 more rows
`

**Comment by milen-sage** [comment]
@andrewelamb could you file a feature request on schematic's repo? There could be a couple of other implementation options (e.g. one would be to retrieve manifest content as json); we can discuss there.

**Comment by andrewelamb** [comment]
[Issue](https://github.com/Sage-Bionetworks/schematic/issues/723)

**Comment by andrewelamb** [comment]
@milen-sage Should I start a feature request for the getProjectManifests endpoint?

**Comment by milen-sage** [comment]
@andrewelamb yes please start a gh issue.

**Comment by andrewelamb** [comment]
[Isssue](https://github.com/Sage-Bionetworks/schematic/issues/731)

**Comment by ychae** [comment]
hi @andrewelamb I see that this ticket is marked Done on the project board, can this ticket be closed?

**Comment by andrewelamb** [comment]
@ychae It's waiting on a review for the PR I made.
